In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('D:/ML_practice/Animal_Multi_Classification/zoo.csv')
data.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [4]:
data.isna().sum()

animal_name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
class_type     0
dtype: int64

In [7]:
data.duplicated().sum()

0

In [14]:
len(data['animal_name'].unique())

100

In [16]:
data['animal_name'].value_counts().sort_values(ascending=False)

frog        2
lark        1
octopus     1
vampire     1
leopard     1
           ..
dolphin     1
catfish     1
seasnake    1
slowworm    1
lobster     1
Name: animal_name, Length: 100, dtype: int64

In [17]:
data_y=data['class_type']
data_y.head()

0    1
1    1
2    4
3    1
4    1
Name: class_type, dtype: int64

In [19]:
data_y.unique()

array([1, 4, 2, 7, 6, 5, 3], dtype=int64)

In [20]:
data_x=data.drop(['class_type'],axis=1)

In [21]:
data_x.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0        1         1         1         0     0     4     0         0        1  
1        1         1         1         0     0     4     1         0        1  
2        1         1         0         0     1     0     1         0        0  
3        1         1         1         0     0     4     0         0        1  
4        1         1         1         0     0     4     1         0        1

In [26]:
data_x=pd.get_dummies(data_x,prefix=['animal_name'])

In [27]:
data_x.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  ...  animal_name_tuatara  animal_name_tuna  animal_name_vampire  \
0         1  ...                    0                 0                    0   
1         1  ...                    0                 0                    0   
2         0  ...                    0                 0                    0   
3         1  ...                    0                 0                    0   
4         1  ...                    0                 0                    0   

   animal_name_vole  animal_name_vulture  animal_name_wallaby  \
0                 0                    0                    0   
1                 0                    0                    0   
2                 0                    0                    0   
3                 0                    0                    0   
4                 0                    0                    0   

   animal_name_wasp  animal_name_wolf  animal_name_worm  animal_name_wren  
0                 0                 0                 0                 0  
1                 0                 0                 0                 0  
2                 0                 0                 0                 0  
3                 0                 0                 0                 0  
4                 0                 0                 0                 0  

[5 rows x 116 columns]

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.20)

In [29]:
from sklearn.neighbors import KNeighborsClassifier
ani_classifier = KNeighborsClassifier(n_neighbors=4)
ani_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [30]:
predict_animal=ani_classifier.predict(X_test)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predict_animal))
print(classification_report(y_test, predict_animal))

[[10  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  2  1]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         2
           3       0.00      0.00      0.00         1
           4       0.75      1.00      0.86         3
           6       0.50      1.00      0.67         2
           7       1.00      0.33      0.50         3

    accuracy                           0.86        21
   macro avg       0.71      0.72      0.67        21
weighted avg       0.87      0.86      0.83        21



D:\DA\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
model_rndf = RandomForestClassifier()
model_rndf.fit(X_train, y_train)
predict_animal2=model_rndf.predict(X_test)

In [35]:
print(model_rndf.score(X_train, y_train))
print(model_rndf.score(X_test, y_test))

1.0
0.9523809523809523


In [36]:
from sklearn.naive_bayes import GaussianNB

In [37]:
clf=GaussianNB()

In [40]:
clf.fit(X_train,y_train)
clf.predict(X_test)

array([4, 7, 1, 2, 1, 4, 1, 4, 4, 1, 7, 1, 2, 1, 1, 7, 1, 7, 7, 1, 1],
      dtype=int64)

In [41]:
clf.score(X_test,y_test)

0.8571428571428571

In [45]:
from sklearn import svm
classif=svm.SVC(kernel='linear')
classif.fit(X_train,y_train)



SVC(kernel='linear')

In [46]:
classif.predict(X_test)

array([4, 6, 1, 2, 1, 4, 1, 4, 4, 1, 7, 1, 2, 1, 1, 7, 1, 6, 7, 1, 1],
      dtype=int64)

In [47]:
classif.score(X_test,y_test)

0.9523809523809523

In [49]:
from sklearn import tree
clf_dc=tree.DecisionTreeClassifier()
clf_dc=clf_dc.fit(X_train,y_train)

In [50]:
clf_dc.predict(X_test)

array([5, 7, 1, 2, 1, 4, 1, 4, 4, 1, 7, 1, 2, 1, 1, 7, 1, 7, 7, 1, 1],
      dtype=int64)

In [51]:
clf_dc.score(X_test,y_test)

0.8571428571428571